source "https://rubygems.org"

# Updated to latest for new device support (6.7", 6.9" iPhone, 13" iPad)
gem "fastlane", "~> 2.230"

plugins_path = File.join(File.dirname(__FILE__), 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
