import { Quote, MeditationSession } from './api';

export const MOCK_QUOTES: Quote[] = [
  // BUDDHIST WISDOM - Buddha
  {
    id: 1,
    text: 'The mind is everything. What you think you become.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    text: 'Peace comes from within. Do not seek it without.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Inner Peace',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    text: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    text: 'Meditation brings wisdom; lack of meditation leaves ignorance.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    text: 'You yourself, as much as anybody in the entire universe, deserve your love and affection.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Self-Compassion',
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    text: 'The root of suffering is attachment.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    text: 'Nothing can harm you as much as your own thoughts unguarded.',
    author: 'Buddha',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // THÍCH NHẤT HẠNH
  {
    id: 10,
    text: 'The present moment is the only time over which we have dominion.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    text: 'Meditation is not evasion; it is a serene encounter with reality.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    text: 'Breathing in, I calm body and mind. Breathing out, I smile.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 13,
    text: 'Walk as if you are kissing the Earth with your feet.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    text: 'The miracle is not to walk on water. The miracle is to walk on the green earth in the present moment.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },

  // DALAI LAMA
  {
    id: 20,
    text: 'Happiness is not something ready made. It comes from your own actions.',
    author: 'Dalai Lama',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 21,
    text: 'If you want others to be happy, practice compassion. If you want to be happy, practice compassion.',
    author: 'Dalai Lama',
    languageCode: 'en',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },
  {
    id: 22,
    text: 'The purpose of our lives is to be happy.',
    author: 'Dalai Lama',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 23,
    text: 'Sleep is the best meditation.',
    author: 'Dalai Lama',
    languageCode: 'en',
    category: 'Rest',
    createdAt: new Date().toISOString(),
  },

  // JON KABAT-ZINN
  {
    id: 30,
    text: 'The goal of meditation is not to get rid of thoughts or emotions. The goal is to become more aware of your thoughts and emotions.',
    author: 'Jon Kabat-Zinn',
    languageCode: 'en',
    category: 'Awareness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 31,
    text: 'Mindfulness is about being fully awake in our lives.',
    author: 'Jon Kabat-Zinn',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 32,
    text: 'You can\'t stop the waves, but you can learn to surf.',
    author: 'Jon Kabat-Zinn',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 33,
    text: 'The little things? The little moments? They aren\'t little.',
    author: 'Jon Kabat-Zinn',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // ECKHART TOLLE
  {
    id: 40,
    text: 'Wherever you are, be there totally.',
    author: 'Eckhart Tolle',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 41,
    text: 'Realize deeply that the present moment is all you have. Make the NOW the primary focus of your life.',
    author: 'Eckhart Tolle',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 42,
    text: 'The power for creating a better future is contained in the present moment.',
    author: 'Eckhart Tolle',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 43,
    text: 'Stillness is the language God speaks, and everything else is a bad translation.',
    author: 'Eckhart Tolle',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // RUMI (Sufi)
  {
    id: 50,
    text: 'The quieter you become, the more you can hear.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 51,
    text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 52,
    text: 'Let silence be the art you practice.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 53,
    text: 'The wound is the place where the Light enters you.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Healing',
    createdAt: new Date().toISOString(),
  },

  // LAO TZU (Taoist)
  {
    id: 60,
    text: 'Nature does not hurry, yet everything is accomplished.',
    author: 'Lao Tzu',
    languageCode: 'en',
    category: 'Patience',
    createdAt: new Date().toISOString(),
  },
  {
    id: 61,
    text: 'Silence is a source of great strength.',
    author: 'Lao Tzu',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 62,
    text: 'When I let go of what I am, I become what I might be.',
    author: 'Lao Tzu',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 63,
    text: 'Knowing others is intelligence; knowing yourself is true wisdom.',
    author: 'Lao Tzu',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 64,
    text: 'Do you have the patience to wait till your mud settles and the water is clear?',
    author: 'Lao Tzu',
    languageCode: 'en',
    category: 'Patience',
    createdAt: new Date().toISOString(),
  },

  // ALAN WATTS
  {
    id: 70,
    text: 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.',
    author: 'Alan Watts',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 71,
    text: 'You are the universe experiencing itself.',
    author: 'Alan Watts',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 72,
    text: 'The meaning of life is just to be alive. It is so plain and so obvious and so simple.',
    author: 'Alan Watts',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 73,
    text: 'Muddy water is best cleared by leaving it alone.',
    author: 'Alan Watts',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // JACK KORNFIELD
  {
    id: 80,
    text: 'In the end, just three things matter: How well we have lived. How well we have loved. How well we have learned to let go.',
    author: 'Jack Kornfield',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 81,
    text: 'The trouble is, you think you have time.',
    author: 'Jack Kornfield',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 82,
    text: 'Meditation is not about getting anywhere else. It is about being where you are and knowing it.',
    author: 'Jack Kornfield',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // SHARON SALZBERG
  {
    id: 90,
    text: 'Meditation is the ultimate mobile device; you can use it anywhere, anytime, unobtrusively.',
    author: 'Sharon Salzberg',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 91,
    text: 'You don\'t have to be good at meditating. You just have to do it.',
    author: 'Sharon Salzberg',
    languageCode: 'en',
    category: 'Encouragement',
    createdAt: new Date().toISOString(),
  },
  {
    id: 92,
    text: 'Mindfulness isn\'t difficult, we just need to remember to do it.',
    author: 'Sharon Salzberg',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // PEMA CHÖDRÖN
  {
    id: 100,
    text: 'The most fundamental aggression to ourselves is remaining ignorant by not having the courage to look at ourselves honestly and gently.',
    author: 'Pema Chödrön',
    languageCode: 'en',
    category: 'Self-Awareness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 101,
    text: 'Compassion is not a relationship between the healer and the wounded. It\'s a relationship between equals.',
    author: 'Pema Chödrön',
    languageCode: 'en',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },
  {
    id: 102,
    text: 'Meditation practice isn\'t about trying to throw ourselves away and become something better. It\'s about befriending who we are.',
    author: 'Pema Chödrön',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // MARCUS AURELIUS (Stoic)
  {
    id: 110,
    text: 'You have power over your mind - not outside events. Realize this, and you will find strength.',
    author: 'Marcus Aurelius',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 111,
    text: 'Confine yourself to the present.',
    author: 'Marcus Aurelius',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 112,
    text: 'When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.',
    author: 'Marcus Aurelius',
    languageCode: 'en',
    category: 'Gratitude',
    createdAt: new Date().toISOString(),
  },

  // DOGEN (Zen)
  {
    id: 120,
    text: 'To study the self is to forget the self. To forget the self is to be enlightened by all things.',
    author: 'Dogen',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },
  {
    id: 121,
    text: 'Sitting peacefully doing nothing, spring comes and the grass grows by itself.',
    author: 'Dogen',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },

  // SHUNRYU SUZUKI (Zen)
  {
    id: 130,
    text: 'In the beginner\'s mind there are many possibilities, but in the expert\'s there are few.',
    author: 'Shunryu Suzuki',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },
  {
    id: 131,
    text: 'The most important point is to accept yourself and stand on your two feet.',
    author: 'Shunryu Suzuki',
    languageCode: 'en',
    category: 'Self-Acceptance',
    createdAt: new Date().toISOString(),
  },

  // PARAMAHANSA YOGANANDA (Vedic)
  {
    id: 140,
    text: 'The season of failure is the best time for sowing the seeds of success.',
    author: 'Paramahansa Yogananda',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 141,
    text: 'Calmness is the ideal state in which we should receive all life\'s experiences.',
    author: 'Paramahansa Yogananda',
    languageCode: 'en',
    category: 'Calmness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 142,
    text: 'The happiness of one\'s own heart alone cannot satisfy the soul; one must try to include, as necessary to one\'s own happiness, the happiness of others.',
    author: 'Paramahansa Yogananda',
    languageCode: 'en',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },

  // KRISHNAMURTI
  {
    id: 150,
    text: 'The ability to observe without evaluating is the highest form of intelligence.',
    author: 'Jiddu Krishnamurti',
    languageCode: 'en',
    category: 'Awareness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 151,
    text: 'Meditation is the ending of thought. It is only then that there is a different dimension which is beyond time.',
    author: 'Jiddu Krishnamurti',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 152,
    text: 'The moment you have in your heart this extraordinary thing called love and feel the depth, the delight, the ecstasy of it, you will discover that for you the world is transformed.',
    author: 'Jiddu Krishnamurti',
    languageCode: 'en',
    category: 'Love',
    createdAt: new Date().toISOString(),
  },

  // VARIOUS WISDOM TRADITIONS
  {
    id: 160,
    text: 'Meditation is a way for nourishing and blossoming the divinity within you.',
    author: 'Amit Ray',
    languageCode: 'en',
    category: 'Growth',
    createdAt: new Date().toISOString(),
  },
  {
    id: 161,
    text: 'Quiet the mind and the soul will speak.',
    author: 'Ma Jaya Sati Bhagavati',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 162,
    text: 'Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 163,
    text: 'Your calm mind is the ultimate weapon against your challenges.',
    author: 'Bryant McGill',
    languageCode: 'en',
    category: 'Calmness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 164,
    text: 'The thing about meditation is: You become more and more you.',
    author: 'David Lynch',
    languageCode: 'en',
    category: 'Self-Discovery',
    createdAt: new Date().toISOString(),
  },
  {
    id: 165,
    text: 'Meditation is not about stopping thoughts, but recognizing that we are more than our thoughts and our feelings.',
    author: 'Arianna Huffington',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 166,
    text: 'Within you, there is a stillness and a sanctuary to which you can retreat at any time and be yourself.',
    author: 'Hermann Hesse',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 167,
    text: 'Meditation is the tongue of the soul and the language of our spirit.',
    author: 'Jeremy Taylor',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 168,
    text: 'In meditation, we discover our inherent restlessness. Sometimes we get up and leave. Sometimes we sit there but our bodies wiggle and squirm and our minds go far away.',
    author: 'Pema Chödrön',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 169,
    text: 'Be here now. Be someplace else later. Is that so complicated?',
    author: 'David M. Bader',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 170,
    text: 'Meditation is all about the pursuit of nothingness. It\'s like the ultimate rest.',
    author: 'Hugh Jackman',
    languageCode: 'en',
    category: 'Rest',
    createdAt: new Date().toISOString(),
  },

  // MORE RUMI (Sufi)
  {
    id: 180,
    text: 'Don\'t grieve. Anything you lose comes round in another form.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 181,
    text: 'What you seek is seeking you.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 182,
    text: 'The cure for pain is in the pain.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Healing',
    createdAt: new Date().toISOString(),
  },
  {
    id: 183,
    text: 'Respond to every call that excites your spirit.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Inspiration',
    createdAt: new Date().toISOString(),
  },

  // AJAHN CHAH (Thai Forest Buddhist)
  {
    id: 190,
    text: 'If you let go a little, you will have a little peace. If you let go a lot, you will have a lot of peace.',
    author: 'Ajahn Chah',
    languageCode: 'en',
    category: 'Letting Go',
    createdAt: new Date().toISOString(),
  },
  {
    id: 191,
    text: 'Do not try to become anything. Do not make yourself into anything. Do not be a meditator. Do not become enlightened. When you sit, let it be. When you walk, let it be.',
    author: 'Ajahn Chah',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 192,
    text: 'The heart is just the heart; thoughts are just thoughts. Let things be just as they are.',
    author: 'Ajahn Chah',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },

  // RAM DASS
  {
    id: 200,
    text: 'Be here now.',
    author: 'Ram Dass',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 201,
    text: 'We\'re all just walking each other home.',
    author: 'Ram Dass',
    languageCode: 'en',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },
  {
    id: 202,
    text: 'The quieter you become, the more you can hear.',
    author: 'Ram Dass',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 203,
    text: 'Treat everyone you meet like God in drag.',
    author: 'Ram Dass',
    languageCode: 'en',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },

  // MOOJI (Contemporary Advaita)
  {
    id: 210,
    text: 'Don\'t worry about the future. If you are abiding in the now, the future will unfold according to the now.',
    author: 'Mooji',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 211,
    text: 'You are the unchanging seer of all that changes.',
    author: 'Mooji',
    languageCode: 'en',
    category: 'Self-Awareness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 212,
    text: 'Step into the fire of self-discovery. This fire will not burn you, it will only burn what you are not.',
    author: 'Mooji',
    languageCode: 'en',
    category: 'Self-Discovery',
    createdAt: new Date().toISOString(),
  },

  // BHAGAVAD GITA
  {
    id: 220,
    text: 'You have the right to work, but never to the fruit of work.',
    author: 'Bhagavad Gita',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 221,
    text: 'When meditation is mastered, the mind is unwavering like the flame of a candle in a windless place.',
    author: 'Bhagavad Gita',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 222,
    text: 'The soul is neither born, and nor does it die.',
    author: 'Bhagavad Gita',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 223,
    text: 'Set your heart upon your work but never its reward.',
    author: 'Bhagavad Gita',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // UPANISHADS
  {
    id: 230,
    text: 'You are what your deep, driving desire is. As your desire is, so is your will. As your will is, so is your deed. As your deed is, so is your destiny.',
    author: 'Brihadaranyaka Upanishad',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 231,
    text: 'From the unreal lead me to the real. From darkness lead me to light. From death lead me to immortality.',
    author: 'Brihadaranyaka Upanishad',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 232,
    text: 'That which is the finest essence—this whole world has that as its soul. That is Reality. That is Atman. That art thou.',
    author: 'Chandogya Upanishad',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // SENECA (Stoic)
  {
    id: 240,
    text: 'He suffers more than necessary, who suffers before it is necessary.',
    author: 'Seneca',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 241,
    text: 'We suffer more often in imagination than in reality.',
    author: 'Seneca',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 242,
    text: 'True happiness is to enjoy the present, without anxious dependence upon the future.',
    author: 'Seneca',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 243,
    text: 'Wherever there is a human being, there is an opportunity for kindness.',
    author: 'Seneca',
    languageCode: 'en',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },

  // EPICTETUS (Stoic)
  {
    id: 250,
    text: 'It\'s not what happens to you, but how you react to it that matters.',
    author: 'Epictetus',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 251,
    text: 'First say to yourself what you would be; and then do what you have to do.',
    author: 'Epictetus',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 252,
    text: 'He who laughs at himself never runs out of things to laugh at.',
    author: 'Epictetus',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // THOMAS MERTON (Christian Contemplative)
  {
    id: 260,
    text: 'The beginning of love is the will to let those we love be perfectly themselves, and not to twist them to fit our own image.',
    author: 'Thomas Merton',
    languageCode: 'en',
    category: 'Love',
    createdAt: new Date().toISOString(),
  },
  {
    id: 261,
    text: 'Happiness is not a matter of intensity but of balance, order, rhythm and harmony.',
    author: 'Thomas Merton',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 262,
    text: 'The biggest human temptation is to settle for too little.',
    author: 'Thomas Merton',
    languageCode: 'en',
    category: 'Inspiration',
    createdAt: new Date().toISOString(),
  },

  // MEISTER ECKHART (Christian Mystic)
  {
    id: 270,
    text: 'The eye through which I see God is the same eye through which God sees me.',
    author: 'Meister Eckhart',
    languageCode: 'en',
    category: 'Mysticism',
    createdAt: new Date().toISOString(),
  },
  {
    id: 271,
    text: 'Be willing to be a beginner every single morning.',
    author: 'Meister Eckhart',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 272,
    text: 'Silence is God\'s first language.',
    author: 'Meister Eckhart',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // HAFIZ (Persian Sufi Poet)
  {
    id: 280,
    text: 'I wish I could show you, when you are lonely or in darkness, the astonishing light of your own being.',
    author: 'Hafiz',
    languageCode: 'en',
    category: 'Self-Discovery',
    createdAt: new Date().toISOString(),
  },
  {
    id: 281,
    text: 'Fear is the cheapest room in the house. I would like to see you living in better conditions.',
    author: 'Hafiz',
    languageCode: 'en',
    category: 'Courage',
    createdAt: new Date().toISOString(),
  },
  {
    id: 282,
    text: 'Even after all this time, the sun never says to the earth, "You owe me." Look what happens with a love like that. It lights the whole sky.',
    author: 'Hafiz',
    languageCode: 'en',
    category: 'Love',
    createdAt: new Date().toISOString(),
  },

  // KABIR (Indian Mystic Poet)
  {
    id: 290,
    text: 'Wherever you are is the entry point.',
    author: 'Kabir',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 291,
    text: 'The river that flows in you also flows in me.',
    author: 'Kabir',
    languageCode: 'en',
    category: 'Unity',
    createdAt: new Date().toISOString(),
  },
  {
    id: 292,
    text: 'Be quiet in your mind, quiet in your senses, and also quiet in your body. Then, when all these are quiet, don\'t do anything. In that state truth will reveal itself to you.',
    author: 'Kabir',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // BASHO (Japanese Haiku Master)
  {
    id: 300,
    text: 'Do not seek to follow in the footsteps of the wise. Seek what they sought.',
    author: 'Matsuo Basho',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 301,
    text: 'The temple bell stops but I still hear the sound coming out of the flowers.',
    author: 'Matsuo Basho',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },

  // MORE ZEN MASTERS
  {
    id: 310,
    text: 'Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.',
    author: 'Zen Proverb',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },
  {
    id: 311,
    text: 'The obstacle is the path.',
    author: 'Zen Proverb',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },
  {
    id: 312,
    text: 'Let go or be dragged.',
    author: 'Zen Proverb',
    languageCode: 'en',
    category: 'Letting Go',
    createdAt: new Date().toISOString(),
  },
  {
    id: 313,
    text: 'No snowflake ever falls in the wrong place.',
    author: 'Zen Proverb',
    languageCode: 'en',
    category: 'Zen',
    createdAt: new Date().toISOString(),
  },

  // S.N. GOENKA (Vipassana Teacher)
  {
    id: 320,
    text: 'The art of living is to die each moment and to be reborn each moment.',
    author: 'S.N. Goenka',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 321,
    text: 'Meditation is accepting whatever is happening to you at the present moment.',
    author: 'S.N. Goenka',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 322,
    text: 'Peace and negativity cannot coexist just as light and darkness cannot coexist.',
    author: 'S.N. Goenka',
    languageCode: 'en',
    category: 'Inner Peace',
    createdAt: new Date().toISOString(),
  },

  // ADYASHANTI (Contemporary Nondual Teacher)
  {
    id: 330,
    text: 'The true intelligence is silence, the ability to be still and allow truth to reveal itself.',
    author: 'Adyashanti',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 331,
    text: 'Enlightenment is a destructive process. It has nothing to do with becoming better or being happier.',
    author: 'Adyashanti',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 332,
    text: 'The light of consciousness has no mind to change or alter anything. There is no sense that anything needs to change, but it does change.',
    author: 'Adyashanti',
    languageCode: 'en',
    category: 'Awareness',
    createdAt: new Date().toISOString(),
  },

  // SADHGURU (Contemporary Yogi)
  {
    id: 340,
    text: 'Meditation means to know life beyond the sphere of the physical; to know and experience life not just at the surface but at the source.',
    author: 'Sadhguru',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 341,
    text: 'The sign of intelligence is that you are constantly wondering. Idiots are always dead sure about every damn thing they are doing in their life.',
    author: 'Sadhguru',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 342,
    text: 'If you resist change, you resist life.',
    author: 'Sadhguru',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },

  // JOSEPH GOLDSTEIN (Insight Meditation)
  {
    id: 350,
    text: 'Meditation is not about feeling a certain way. It\'s about feeling the way you feel.',
    author: 'Joseph Goldstein',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 351,
    text: 'The attitude of interest is what keeps us present.',
    author: 'Joseph Goldstein',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // SWAMI VIVEKANANDA (Vedanta)
  {
    id: 360,
    text: 'All the powers in the universe are already ours. It is we who have put our hands before our eyes and cry that it is dark.',
    author: 'Swami Vivekananda',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 361,
    text: 'Arise, awake, and stop not until the goal is reached.',
    author: 'Swami Vivekananda',
    languageCode: 'en',
    category: 'Inspiration',
    createdAt: new Date().toISOString(),
  },
  {
    id: 362,
    text: 'You cannot believe in God until you believe in yourself.',
    author: 'Swami Vivekananda',
    languageCode: 'en',
    category: 'Self-Discovery',
    createdAt: new Date().toISOString(),
  },

  // NISARGADATTA MAHARAJ (Advaita Vedanta)
  {
    id: 370,
    text: 'Wisdom tells me I am nothing. Love tells me I am everything. Between the two my life flows.',
    author: 'Nisargadatta Maharaj',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 371,
    text: 'The real does not die, the unreal never lived.',
    author: 'Nisargadatta Maharaj',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 372,
    text: 'Once you realize that the road is the goal and that you are always on the road, not to reach a goal, but to enjoy its beauty and its wisdom, life ceases to be a task and becomes natural and simple.',
    author: 'Nisargadatta Maharaj',
    languageCode: 'en',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // RAMANA MAHARSHI (Advaita)
  {
    id: 380,
    text: 'Your own Self-Realization is the greatest service you can render the world.',
    author: 'Ramana Maharshi',
    languageCode: 'en',
    category: 'Self-Discovery',
    createdAt: new Date().toISOString(),
  },
  {
    id: 381,
    text: 'Silence is the true upadesh (teaching). It is the perfect upadesh.',
    author: 'Ramana Maharshi',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 382,
    text: 'The degree of freedom from unwanted thoughts and the degree of concentration on a single thought are the measures to gauge spiritual progress.',
    author: 'Ramana Maharshi',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // CONTEMPORARY WISDOM
  {
    id: 390,
    text: 'Almost everything will work again if you unplug it for a few minutes, including you.',
    author: 'Anne Lamott',
    languageCode: 'en',
    category: 'Rest',
    createdAt: new Date().toISOString(),
  },
  {
    id: 391,
    text: 'Meditation practice is simple—relentlessly simple.',
    author: 'Shinzen Young',
    languageCode: 'en',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 392,
    text: 'Feelings are just visitors. Let them come and go.',
    author: 'Mooji',
    languageCode: 'en',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 393,
    text: 'The soul always knows what to do to heal itself. The challenge is to silence the mind.',
    author: 'Caroline Myss',
    languageCode: 'en',
    category: 'Healing',
    createdAt: new Date().toISOString(),
  },
  {
    id: 394,
    text: 'Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.',
    author: 'Rumi',
    languageCode: 'en',
    category: 'Love',
    createdAt: new Date().toISOString(),
  },
  {
    id: 395,
    text: 'Life is available only in the present moment.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 396,
    text: 'If the doors of perception were cleansed, everything would appear to man as it is: infinite.',
    author: 'William Blake',
    languageCode: 'en',
    category: 'Awareness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 397,
    text: 'Knowing yourself is the beginning of all wisdom.',
    author: 'Aristotle',
    languageCode: 'en',
    category: 'Self-Awareness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 398,
    text: 'The only journey is the one within.',
    author: 'Rainer Maria Rilke',
    languageCode: 'en',
    category: 'Self-Discovery',
    createdAt: new Date().toISOString(),
  },
  {
    id: 399,
    text: 'In the midst of movement and chaos, keep stillness inside of you.',
    author: 'Deepak Chopra',
    languageCode: 'en',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 400,
    text: 'The present moment is filled with joy and happiness. If you are attentive, you will see it.',
    author: 'Thích Nhất Hạnh',
    languageCode: 'en',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_SESSIONS: MeditationSession[] = [
  // TRADITIONAL BEGINNER SESSIONS (Level 1)
  {
    id: 1,
    title: 'Morning Awakening',
    description: 'Start your day with clarity and focus. A gentle 5-minute practice to center yourself.',
    languageCode: 'en',
    durationSeconds: 300, // 5 minutes
    level: 1,
    cultureTag: 'traditional',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Breath Awareness',
    description: 'Focus on your natural breath. A foundational practice for beginners.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 1,
    cultureTag: 'traditional',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Body Scan Relaxation',
    description: 'Progressive relaxation technique moving attention through the body.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'traditional',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Loving Kindness',
    description: 'Cultivate compassion and goodwill toward yourself and others.',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'traditional',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: 'Deep Meditation',
    description: 'Extended practice for experienced meditators. Dive into stillness.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'traditional',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // OCCASION-SPECIFIC SESSIONS
  // Morning Energy
  {
    id: 10,
    title: 'Morning Energy Boost',
    description: 'Energize your body and mind for the day ahead with breath techniques.',
    languageCode: 'en',
    durationSeconds: 480, // 8 minutes
    level: 1,
    cultureTag: 'occasion_morning',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    title: 'Sunrise Meditation',
    description: 'Greet the new day with gratitude and intention setting.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'occasion_morning',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Stress Relief
  {
    id: 20,
    title: 'Quick Stress Relief',
    description: 'Release tension in just 5 minutes. Perfect for work breaks.',
    languageCode: 'en',
    durationSeconds: 300, // 5 minutes
    level: 1,
    cultureTag: 'occasion_stress',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 21,
    title: 'Deep Stress Release',
    description: 'Comprehensive stress relief through progressive relaxation.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'occasion_stress',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Sleep Preparation
  {
    id: 30,
    title: 'Evening Wind Down',
    description: 'Release the day\'s tensions and prepare for restful sleep.',
    languageCode: 'en',
    durationSeconds: 480, // 8 minutes
    level: 1,
    cultureTag: 'occasion_sleep',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 31,
    title: 'Sleep Sanctuary',
    description: 'Deep body scan and relaxation for profound rest.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 2,
    cultureTag: 'occasion_sleep',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Deep Focus
  {
    id: 40,
    title: 'Concentration Builder',
    description: 'Sharpen your focus and eliminate distractions.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'occasion_focus',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 41,
    title: 'Flow State Activation',
    description: 'Enter deep concentration for work or study.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 3,
    cultureTag: 'occasion_focus',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Anxiety Release
  {
    id: 50,
    title: 'Calm Anxiety',
    description: 'Soothe anxious thoughts with gentle breath awareness.',
    languageCode: 'en',
    durationSeconds: 420, // 7 minutes
    level: 1,
    cultureTag: 'occasion_anxiety',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 51,
    title: 'Anxiety Release Practice',
    description: 'Ground yourself and release worry through body awareness.',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'occasion_anxiety',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Grief & Loss
  {
    id: 60,
    title: 'Healing Through Grief',
    description: 'A gentle space to honor loss and find peace.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'occasion_grief',
    ambientFrequency: 528, // Healing frequency
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 61,
    title: 'Embracing Loss',
    description: 'Compassionate meditation for processing difficult emotions.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'occasion_grief',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Gratitude Practice
  {
    id: 70,
    title: 'Gratitude Reflection',
    description: 'Cultivate appreciation for life\'s blessings.',
    languageCode: 'en',
    durationSeconds: 480, // 8 minutes
    level: 1,
    cultureTag: 'occasion_gratitude',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 71,
    title: 'Deep Gratitude Journey',
    description: 'Explore profound thankfulness and joy.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'occasion_gratitude',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Creative Inspiration
  {
    id: 80,
    title: 'Creative Awakening',
    description: 'Unlock your creative potential through open awareness.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'occasion_creativity',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 81,
    title: 'Inspiration Flow',
    description: 'Access your inner muse and creative genius.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 3,
    cultureTag: 'occasion_creativity',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // CULTURALLY DIVERSE MEDITATION SESSIONS
  // Zen (Japanese)
  {
    id: 100,
    title: 'Zazen - Zen Sitting',
    description: 'Traditional Zen meditation. Just sitting, observing breath and thoughts.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'zen',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 101,
    title: 'Kinhin - Zen Walking',
    description: 'Slow, mindful walking between sitting periods.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'zen',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 102,
    title: 'Beginner Zazen',
    description: 'Introduction to Zen sitting meditation practice.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 1,
    cultureTag: 'zen',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Vipassana (Buddhist)
  {
    id: 110,
    title: 'Vipassana Body Scan',
    description: 'Systematic awareness of sensations throughout the body.',
    languageCode: 'en',
    durationSeconds: 1800, // 30 minutes
    level: 4,
    cultureTag: 'vipassana',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 111,
    title: 'Insight Meditation',
    description: 'Observe the impermanent nature of all phenomena.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'vipassana',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 112,
    title: 'Beginner Vipassana',
    description: 'Introduction to insight meditation practice.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'vipassana',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Vedic (Hindu)
  {
    id: 120,
    title: 'Om Meditation',
    description: 'Chant and meditate on the primordial sound Om.',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'vedic',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 121,
    title: 'Transcendental Meditation',
    description: 'Settle into deep inner silence with mantra practice.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'vedic',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 122,
    title: 'Chakra Awareness',
    description: 'Journey through the seven energy centers.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'vedic',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Taoist (Chinese)
  {
    id: 130,
    title: 'Qigong Meditation',
    description: 'Cultivate Qi energy through breath and visualization.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'taoist',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 131,
    title: 'Inner Smile Practice',
    description: 'Taoist meditation for cultivating inner peace and joy.',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'taoist',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 132,
    title: 'Wu Wei - Effortless Being',
    description: 'Flow with the natural way of things.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'taoist',
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Sufi (Islamic)
  {
    id: 140,
    title: 'Dhikr - Remembrance',
    description: 'Rhythmic remembrance of the Divine.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'sufi',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 141,
    title: 'Muraqaba - Heart Meditation',
    description: 'Sufi contemplation of the heart center.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'sufi',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 142,
    title: 'Breath of Compassion',
    description: 'Sufi breathing practice for opening the heart.',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'sufi',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Christian Contemplative
  {
    id: 150,
    title: 'Centering Prayer',
    description: 'Silent communion with God through sacred word.',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 2,
    cultureTag: 'christian',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 151,
    title: 'Lectio Divina',
    description: 'Contemplative scripture reading and meditation.',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'christian',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 152,
    title: 'Contemplative Silence',
    description: 'Rest in the presence of the Divine.',
    languageCode: 'en',
    durationSeconds: 1500, // 25 minutes
    level: 3,
    cultureTag: 'christian',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 153,
    title: 'Breath Prayer',
    description: 'Rhythmic prayer synchronized with breathing.',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 1,
    cultureTag: 'christian',
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
];
